# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0006_auto_20180316_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('body_text', models.TextField(blank=True, null=True, verbose_name='Post Body Text')),
                ('projects', models.ManyToManyField(to='package.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
