# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatepost',
            name='link',
            field=models.CharField(default='', max_length=254, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='updatepost',
            name='title',
            field=models.CharField(default='', max_length=254, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='updatepost',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Publish Date'),
        ),
    ]
