stages:
  - build
  - deploy

image: docker:git

services:
  - docker:dind

variables:
  STACK_NAME: hiveprojects
  CERTS: ~/.docker

build:
  stage: build
  only:
    - develop
    - production
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  script:
    - docker build
      -f app/Dockerfile app
      -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
      --cache-from $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  after_script:
    - docker images

.update: &update
  stage: deploy

  before_script:
    - mkdir -p $CERTS/
    - echo "$CORE_SWARM_TLSCACERT" > $CERTS/ca.pem
    - echo "$CORE_SWARM_TLSCERT" > $CERTS/cert.pem
    - echo "$CORE_SWARM_TLSKEY" > $CERTS/key.pem
    - echo $CORE_DEPLOY_TOKEN_KEY | DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify login -u $CORE_DEPLOY_TOKEN_NAME $CI_REGISTRY --password-stdin
    - DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  script:
    - DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify service update --image $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA --update-failure-action rollback --update-order start-first ${STACK_NAME}-${STACK_ENV}_app
    - DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify service update --image $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA --update-failure-action rollback --update-order start-first ${STACK_NAME}-${STACK_ENV}_cron

.deploy: &deploy
  stage: deploy
  when: manual

  before_script:
    - mkdir -p $CERTS/
    - echo "$CORE_SWARM_TLSCACERT" > $CERTS/ca.pem
    - echo "$CORE_SWARM_TLSCERT" > $CERTS/cert.pem
    - echo "$CORE_SWARM_TLSKEY" > $CERTS/key.pem
    - echo $CORE_DEPLOY_TOKEN_KEY | DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify login -u $CORE_DEPLOY_TOKEN_NAME $CI_REGISTRY --password-stdin
    # Pull all necessary images before deploy
    - cat ${STACK_FILE} | grep -oE 'image:([ a-zA-Z0-9\:\/\.-]*)' | sed "s~image:~~g" | while read -r image ; do DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify pull $image; done

  script:
    - DOCKER_CERT_PATH=$CERTS docker -H $CORE_SWARM_HOST --tlsverify stack deploy -c ${STACK_FILE} --with-registry-auth ${STACK_NAME}-${STACK_ENV}


update-staging:
  variables:
    STACK_ENV: staging
  environment:
    name: staging
    url: https://staging.hiveprojects.io
  only:
    - develop
  <<: *update

update-production:
  variables:
    STACK_ENV: production
  environment:
    name: production
    url: https://hiveprojects.io
  only:
    - production
  <<: *update

deploy-staging-stack:
  variables:
    STACK_FILE: stack/docker-compose.staging.yml
    STACK_ENV: staging
  environment:
    name: staging
    url: https://staging.hiveprojects.io
  only:
    - develop
  <<: *deploy

deploy-production-stack:
  variables:
    STACK_FILE: stack/docker-compose.production.yml
    STACK_ENV: production
  environment:
    name: production
    url: https://hiveprojects.io
  only:
    - production
  <<: *deploy

