version: "3.7"
services:

  app:
    build:
      context: ../app
    command: /start.sh
    volumes:
      - ../app:/app
      - media:/data/media
      - static:/data/static
    env_file:
      - ../app/.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media:/data/media
      - static:/data/static
      - ./nginx/localhost.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    volumes:
    - db_redis:/data

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hiveprojects
      - POSTGRES_USER=hiveprojects
    volumes:
    - db_postgres:/var/lib/postgresql/data

volumes:
  db_redis:
  db_postgres:
  media:
  static:
