version: "3.7"
services:

  app:
    image: registry.gitlab.com/engrave/hiveprojects/develop:latest
      command: /start.sh
      hostname: app
      env_file:
        - ${PRODUCTION_ENV_CONFIG}
      volumes:
        - media:/data/media
        - static:/data/static
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/health_check"]
        interval: 1m
        timeout: 10s
        retries: 3
        start_period: 30s
      networks:
        - app

  cron:
    image: registry.gitlab.com/engrave/hiveprojects/develop:latest
    hostname: cron
    command: /configure_and_run_cron.sh
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    configs:
      - source: ENV_CONFIG
        target: /app/.env
    networks:
      - app

  nginx:
    image: nginx:alpine
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/hiveprojects.conf
    volumes:
      - media:/data/media
      - static:/data/static
    networks:
      - app
      - infrastructure

  redis:
    image: redis
    volumes:
      - db_redis:/data
    networks:
      - app

  postgres:
    image: postgres
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app

volumes:
  db_redis:
  db_postgres:
  media:
  static:

configs:
  NGINX_CONFIG:
    file: ./nginx/production.conf
    name: NGINX_CONFIG-${CI_COMMIT_SHA}
  ENV_CONFIG:
    file: ${PRODUCTION_ENV_CONFIG}
    name: ENV_CONFIG-${CI_COMMIT_SHA}

networks:
  app:
  infrastructure:
    external: true
