version: "3.7"
services:

  app:
    image: registry.gitlab.com/engrave/hiveprojects/production:latest
    command: /start.sh
    hostname: app
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    volumes:
      - media:/data/media
      - static:/data/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health_check"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app

  cron:
    image: registry.gitlab.com/engrave/hiveprojects/production:latest
    hostname: cron
    command: /configure_and_run_cron.sh
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    configs:
      - source: ENV_CONFIG
        target: /app/.env
    networks:
      - app

  nginx:
    image: nginx:alpine
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/hiveprojects.conf
      - source: MAINTENANCE_PAGE
        target: /var/www/maintenance/maintenance.html
    volumes:
      - media:/data/media
      - static:/data/static
    networks:
      - app
      - infrastructure

  redis:
    image: redis:6.0.8
    volumes:
      - db_redis:/data
    networks:
      - app

  postgres:
    image: postgres:12.4
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app

  pgbackup:
    image: registry.gitlab.com/engrave/postgres-backup-s3:12.4
    env_file:
      - ${PRODUCTION_ENV_CONFIG}
    environment:
      SCHEDULE: '@daily'
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: backups/hiveprojects/production/database
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      POSTGRES_HOST: postgres
      FILENAME: db.sql.gz
    networks:
      - app

  files-backup:
    image: registry.gitlab.com/engrave/directory-backup-s3:latest
    volumes:
      - media:/data/media
    environment:
      SCHEDULE: '@daily'
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: hiveprojects/production/files
      SOURCE_PATH: /data/media

volumes:
  db_redis:
  db_postgres:
  media:
  static:

configs:
  NGINX_CONFIG:
    file: ./nginx/production.conf
    name: NGINX_CONFIG-${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}
  MAINTENANCE_PAGE:
    file: ./nginx/maintenance/maintenance.html
    name: MAINTENANCE_PAGE-${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}
  ENV_CONFIG:
    file: ${PRODUCTION_ENV_CONFIG}
    name: ENV_CONFIG-${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}

networks:
  app:
  infrastructure:
    external: true
