version: "3.7"
services:

  app:
    build:
      context: ../app
    command: /start-dev.sh
    volumes:
      - ../app:/app
      - media:/data/media
      - static:/data/static
    env_file:
      - ../app/.env
    ports:
      - "8000:8000"

  redis:
    image: redis:6.0.8
    volumes:
    - db_redis:/data

  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hiveprojects
      - POSTGRES_USER=hiveprojects
    volumes:
    - db_postgres:/var/lib/postgresql/data

volumes:
  db_redis:
  db_postgres:
  media:
  static:
