version: "3.7"
services:

  app:
    image: registry.gitlab.com/engrave/hiveprojects/production:latest
    command: /start.sh
    volumes:
      - media:/data/media
      - static:/data/static
    environment:
      - SITE_TITLE=Hive Projects
      - SITE_URL=https://hiveprojects.io
      - FRAMEWORK_NAME=Hive
      - HIVE_NODES=https://api.hive.blog
      - PROJECT_GITHUB_REPOSITORY_URL=https://gitlab.com/engrave/hiveprojects
      - PROJECT_SLUG_ON_PAGE=hiveprojects
      - DJANGO_SETTINGS_MODULE=settings.production
      - DEFAULT_FROM_EMAIL=Hive Projects <noreply@hiveprojects.io>
      - SERVER_EMAIL=Hive Projects <info@hiveprojects.io>
      - SECRET_KEY=${PRODUCTION_SECRET_KEY}
      - POSTGRES_USER=${PRODUCTION_DB_USER}
      - POSTGRES_PASSWORD=${PRODUCTION_DB_PASSWORD}
      - POSTGRES_DB=${PRODUCTION_DB_DATABASE}
      - HIVESIGNER_APP_ID=${HIVESIGNER_APP_ID}
      - HIVESIGNER_APP_SECRET=${HIVESIGNER_APP_SECRET}
      - DJANGO_MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_SENDER_DOMAIN=${MAILGUN_SENDER_DOMAIN}
      - DJANGO_SENTRY_DSN=${SENTRY_DSN}
      - HIVE_ACCOUNT=${HIVE_USERNAME}
      - HIVE_POSTING_KEY=${HIVE_POSTING_KEY}
      - GITHUB_API_SECRET=${PRODUCTION_GITHUB_API_SECRET}
      - GITHUB_APP_ID=${PRODUCTION_GITHUB_APP_ID}
      - GITHUB_USERNAME=${PRODUCTION_GITHUB_USERNAME}
    networks:
      - app

  nginx:
    image: nginx:alpine
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/hiveprojects.conf
    volumes:
      - media:/data/media
      - static:/data/static
    networks:
      - app
      - infrastructure

  redis:
    image: redis
    volumes:
      - db_redis:/data
    networks:
      - app

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${PRODUCTION_DB_PASSWORD}
      - POSTGRES_USER=${PRODUCTION_DB_USER}
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app

volumes:
  db_redis:
  db_postgres:
  media:
  static:

configs:
  NGINX_CONFIG:
    file: ./nginx/production.conf
    name: NGINX_CONFIG-${CI_COMMIT_SHA}

networks:
  app:
  infrastructure:
    external: true
