version: "3.7"
services:

  app:
    image: registry.gitlab.com/engrave/hiveprojects/develop:latest
    command: /start.sh
    hostname: app
    env_file:
      - ${STAGING_ENV_CONFIG}
    volumes:
      - media:/data/media
      - static:/data/static
    networks:
      - app

  cron:
    image: registry.gitlab.com/engrave/hiveprojects/develop:latest
    hostname: cron
    command: /configure_and_run_cron.sh
    env_file:
      - ${STAGING_ENV_CONFIG}
    networks:
      - app

  nginx:
    image: nginx:alpine
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/hiveprojects.conf
    volumes:
      - media:/data/media
      - static:/data/static
    networks:
      - app
      - infrastructure
  redis:
    image: redis
    volumes:
      - db_redis:/data
    networks:
      - app

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${STAGING_DB_PASSWORD}
      - POSTGRES_USER=${STAGING_DB_USER}
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app
volumes:
  db_redis:
  db_postgres:
  media:
  static:

configs:
  NGINX_CONFIG:
    file: ./nginx/staging.conf
    name: NGINX_CONFIG-${CI_COMMIT_SHA}
networks:
  app:
  infrastructure:
    external: true
